import { $ } from "bun";
import { readdir, stat, rm, mkdir, copyFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dir, "..", "..");
const SERVER = path.resolve(import.meta.dir, "..");
const WEB = path.join(ROOT, "web");
const DIST_SRC = path.join(WEB, "dist");
const DIST_DST = path.join(SERVER, "web-dist");
const EMBEDDED = path.join(SERVER, "src", "embedded.ts");
const OUT_NAME = process.env.AO3HUB_OUT ?? "ao3-hub";
const OUT_DIR = path.join(SERVER, "build");
const OUT_PATH = path.join(OUT_DIR, OUT_NAME);

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".txt": "text/plain; charset=utf-8",
  ".map": "application/json; charset=utf-8",
};

async function listFiles(dir: string, base = dir): Promise<string[]> {
  const out: string[] = [];
  for (const name of await readdir(dir)) {
    const full = path.join(dir, name);
    const s = await stat(full);
    if (s.isDirectory()) out.push(...(await listFiles(full, base)));
    else out.push(path.relative(base, full));
  }
  return out;
}

async function copyDir(src: string, dst: string): Promise<void> {
  await rm(dst, { recursive: true, force: true });
  await mkdir(dst, { recursive: true });
  const entries = await listFiles(src);
  for (const rel of entries) {
    const from = path.join(src, rel);
    const to = path.join(dst, rel);
    await mkdir(path.dirname(to), { recursive: true });
    await copyFile(from, to);
  }
}

function mimeFor(p: string): string {
  const i = p.lastIndexOf(".");
  if (i < 0) return "application/octet-stream";
  return MIME[p.slice(i).toLowerCase()] ?? "application/octet-stream";
}

async function writeEmbedded(files: string[], version: string, builtAt: string): Promise<void> {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/build.ts — do not edit.",
    "",
  ];
  files.forEach((rel, i) => {
    const importPath = "../web-dist/" + rel.replace(/\\/g, "/");
    lines.push(
      `import a${i} from ${JSON.stringify(importPath)} with { type: "file" };`,
    );
  });
  lines.push("");
  lines.push("export const assets: Record<string, () => Response> = {");
  files.forEach((rel, i) => {
    const url = "/" + rel.replace(/\\/g, "/");
    const mt = mimeFor(rel);
    lines.push(
      `  ${JSON.stringify(url)}: () => new Response(Bun.file(a${i}), { headers: { "content-type": ${JSON.stringify(mt)} } }),`,
    );
  });
  lines.push("};");
  lines.push("");
  lines.push(`export const indexHtmlPath: string | null = ${files.length ? "a0" : "null"};`);
  lines.push(`export const BUILD_VERSION: string | null = ${JSON.stringify(version)};`);
  lines.push(`export const BUILD_BUILT_AT: string | null = ${JSON.stringify(builtAt)};`);
  lines.push("");
  await Bun.write(EMBEDDED, lines.join("\n"));
}

async function writeEmptyEmbedded(): Promise<void> {
  await Bun.write(
    EMBEDDED,
    [
      "export const assets: Record<string, () => Response> = {};",
      "export const indexHtmlPath: string | null = null;",
      "export const BUILD_VERSION: string | null = null;",
      "export const BUILD_BUILT_AT: string | null = null;",
      "",
    ].join("\n"),
  );
}

async function getVersion(): Promise<string> {
  const pkg = await Bun.file(path.join(ROOT, "package.json")).json();
  return pkg.version ?? "0.0.0";
}

async function main() {
  console.log("[build] vite build");
  await $`bun run build`.cwd(WEB);

  console.log("[build] copying web/dist -> server/web-dist");
  await copyDir(DIST_SRC, DIST_DST);

  console.log("[build] generating embedded.ts");
  const files = (await listFiles(DIST_DST)).sort((a, b) => {
    if (a === "index.html") return -1;
    if (b === "index.html") return 1;
    return a.localeCompare(b);
  });
  const version = await getVersion();
  const builtAt = new Date().toISOString();
  await writeEmbedded(files, version, builtAt);

  console.log(`[build] compiling -> ${OUT_PATH}  (v${version})`);
  await mkdir(OUT_DIR, { recursive: true });

  const target = process.env.AO3HUB_TARGET;
  const targetFlag = target ? [`--target=${target}`] : [];

  await $`bun build ${targetFlag} --compile --outfile=${OUT_PATH} ${path.join(SERVER, "src/index.ts")}`;

  console.log("[build] restoring empty embedded.ts");
  await writeEmptyEmbedded();
  await rm(DIST_DST, { recursive: true, force: true });

  const stats = await stat(OUT_PATH);
  console.log(
    `[build] done: ${OUT_PATH}  ${(stats.size / 1024 / 1024).toFixed(1)} MB`,
  );
}

await main();
